#!/bin/bash

USERNAME=$(whoami)
DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $NAME $VERSION)
UPTIME=$(uptime -p)

CPU=$(lshw -class processor | grep -m 1 'product' | awk -F ': ' '{print $2}')
CPU_SPEED=$(lshw -class processor | grep -m 1 'size' | awk -F ': ' '{print $2}')
MAX_CPU_SPEED=$(lshw -class processor | grep -m 1 'capacity' | awk -F ': ' '{print $2}')
RAM=$(free -h | awk '/^Mem:/{print $2}')
DISKS=$(lsblk -d -o NAME,MODEL,SIZE | grep -v 'NAME')
VIDEO=$(lshw -class display | grep -m 1 'product' | awk -F ': ' '{print $2}')

FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}')
NETWORK_INTERFACE=$(lshw -class network | grep -m 1 'description' | awk -F ': ' '{print $2}')
INTERFACE_IP=$(ip -o -4 addr show scope global | awk '{print $4}')

USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | paste -sd ',' -)
DISK_SPACE=$(df -h --output=source,pcent | grep '^/dev')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F 'load average:' '{print $2}' | sed 's/ //g')
MEMORY_ALLOCATION=$(free -h)
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | paste -sd ',' -)
UFW_RULES=$(sudo ufw status numbered)

cat <<EOF

System Report generated by $USERNAME, $DATETIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED (Current), $MAX_CPU_SPEED (Maximum)
RAM: $RAM
Disk(s):
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

Interface Name: $NETWORK_INTERFACE
IP Address: $INTERFACE_IP

System Status
-------------
Users Logged In: $USERS_LOGGED_IN
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation:
$MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules:
$UFW_RULES

EOF
